### ISSUE TITLE
Just a Feedback

### ISSUE THREAD

**Issue by nerun** [oschonrock/hibp#8]
Thanks for the [recommendation](https://github.com/HaveIBeenPwned/PwnedPasswordsDownloader/issues/79#issuecomment-2555861412).

Excellent tool. Download is REAL FAST. The hash file is 40% smaller in binary format. The search speed is so fast that I can't compare.

A GREAT addition you've already made is the `--hash` option to hibp-search: this increases the reliability of your tool. I don't need to fear that you're collecting passwords... Sure, I tested it with `firejail --net=none` first, but `--hash` is great and deserves my trust!

Congratulations and thank you very much for the tool!

You can close this after reading.

**Comment by oschonrock** [comment]
Thanks very much for the feedback. Great that you find it easy and fast. 

Some little questions which would be supper useful for me, if I may:

- Which OS are you on? 
- did you use the binaries or build from source?
- have you tried using the `hibp-server`?  that also has `hash` options if you use it like this (see README for details): 
```
curl http://localhost:8082/check/sha1/CBFDAC6008F9CAB4083784CBD1874F76618D2A97
```

- What is your use case? 

Many thanks

**Comment by nerun** [comment]
Linux Debian testing/Trixie, used binaries, not tested the server.

**Comment by oschonrock** [comment]
thanks for info
